openapi: 3.0.0
info:
  title: NuclearTestingAPI
  description: NuclearTesting API Test
  contact:
    name: Tomas O Dalaigh
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Toma5OD/NuclearTestingAPI/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://github.com/Toma5OD/nuclear-testing-api/blob/main/all.json
  description: MY GIT API
paths:
  /test:
    description: Operation to Fetch Location
    get:
      operationId: testGET
      parameters:
      - name: Title
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: "White Sands Missile Range, New Mexico"
      responses:
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tests'
        "400":
          description: Invalid ID supplied
      x-swagger-router-controller: Default
    post:
      description: Add a new test
      operationId: testPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/test'
      responses:
        "201":
          description: Record succesfully added
      x-swagger-router-controller: Default
  /test{id}:
    description: Get Test based on Path Parameter
    get:
      operationId: testidGET
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Succes Response with Path Param
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tests'
      x-swagger-router-controller: Default
components:
  schemas:
    test:
      type: object
      properties:
        title:
          type: string
          example: "White Sands Missile Range, New Mexico"
        lng:
          type: integer
        lat:
          type: integer
        userid:
          type: string
          example: e977583f-0f72-44bb-bd08-a7b2231f4a46
    tests:
      type: array
      items:
        $ref: '#/components/schemas/tests_inner'
    tests_inner:
      properties:
        title:
          type: string
          example: "White Sands Missile Range, New Mexico"
        lng:
          type: integer
        lat:
          type: integer
        userid:
          type: string
          example: e977583f-0f72-44bb-bd08-a7b2231f4a46
      example:
        lng: 0
        title: "White Sands Missile Range, New Mexico"
        userid: e977583f-0f72-44bb-bd08-a7b2231f4a46
        lat: 6
